positionTuple = tuple[int, int, int]
rangeTuple = tuple[int, int]
jsonDict = dict[str, any] 
shootingOptionsList = list[tuple[positionTuple,list[str]]]
# Key: enemy tank id, value: list[tuple[allyTankId, allyPositionToShootAt]]
shootableTanksDict = dict[str, list[tuple[str, positionTuple]]]