TANKS = {
    "SPG": {
        "hp": 1,
        "sp": 1,
        "damage": 1,
        "destructionPoints": 1,
        "minAttackRange": 3,
        "maxAttackRange": 3,
    },
    "LIGHT_TANK": {
        "hp": 1,
        "sp": 3,
        "damage": 1,
        "destructionPoints": 1,
        "minAttackRange": 2,
        "maxAttackRange": 2,
    },
    "HEAVY_TANK": {
        "hp": 3,
        "sp": 1,
        "damage": 1,
        "destructionPoints": 3,
        "minAttackRange": 1,
        "maxAttackRange": 2,
    },
    "MEDIUM_TANK": {
        "hp": 2,
        "sp": 2,
        "damage": 1,
        "destructionPoints": 2,
        "minAttackRange": 2,
        "maxAttackRange": 2,
    },
    "AT_SPG": {
        "hp": 2,
        "sp": 1,
        "damage": 1,
        "destructionPoints": 2,
        "maxAttackDistance": 3,
    },
}